groups:
  - developer

attributes:
  sublime_text:
    preferences:
      font_size: 14
      remember_open_files: false
      tab_size: 2
  osxdefaults:
    computername: ChadsMacbookPro
  git:
    name: Chad Gullickson
    email: chad.gullickson@optum.com
