groups:
  - developer

recipes:
  global:
    - applications::sizeup
    - applications::evernote
    - applications::cask_apps

attributes:
  brew:
    cask_apps:
  sublime_text:
    preferences:
      font_size: 14
      ignored_packages: []
      remember_open_files: false
      tab_size: 2
      vintage_start_in_command_mode: true
      vintage_use_clipboard: true
  git:
    name: Jon Fredeen
    email: jon@fredeen.com
    aliases:
