groups:
  - developer

attributes:
  homebrewalt:
    cask_apps:
      - skitch
      - jing
      - evernote
      - spectacle
  sublime_text:
    preferences:
      font_size: 14
      ignored_packages: []
      remember_open_files: false
      tab_size: 2
      vintage_start_in_command_mode: true
      vintage_use_clipboard: true
  git:
    name: Ryan Sonnek
    email: ryan@codecrate.com
    aliases:
      put: push origin HEAD
      done: commit -a -m
      co: checkout
      undo: reset --hard
      ll: log --summary --stat --pretty=oneline --relative-date
      who: shortlog -n -s --no-merges
      lg: log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
      cleanup: "!~/bin/git-cleanup.sh"
