groups:
  - developer

attributes:
  sublime_text:
    preferences:
      font_size: 14
      remember_open_files: false
      tab_size: 2
  osxdefaults:
    computername: StephensMacbookPro
    finder:
      prefered_view_style: clmv
  homebrewalt:
    apps:
      - wget
      - htop-osx
      - the_silver_searcher
      - python3
    cask_apps:
      - skitch
      - atom
      - iterm2
      - dropbox
      - hipchat
      - lastpass-universal
      - java
      - charles
      - hex-fiend

