recipes:
  global:
    # general tools
    - applications::skype

    # general development
    - dotfiles::bash_it
    - applications::git
    - dotfiles::gitconfig
    - dotfiles::projects

    # rails development stack
    - dotfiles::gem_setup
    - applications::rbenv
    - applications::nodejs
    - applications::phantomjs
    - applications::heroku
    - applications::virtualbox
    - applications::vagrant

    # development tools
    - applications::sublime_text_3
    - applications::github_for_mac
    - applications::mou

attributes:
  workspace_directory: Projects
  dotfiles:
    project_dir: Projects
    projects:
      -
        - thegarage-gitx
        - https://github.com/thegarage/thegarage-gitx.git
      -
        - chef-osxdefaults
        - https://github.com/thegarage/chef-osxdefaults.git
      -
        - chef-applications
        - https://github.com/thegarage/chef-applications.git
      -
        - chef-dotfiles
        - https://github.com/thegarage/chef-dotfiles.git
  rbenv:
    default_ruby: "2.0.0-p353"
    rubies:
      2.0.0-p353: {}
  vagrant_plugins:
    - vagrant-berkshelf
    - vagrant-omnibus
  terminal:
    color_scheme: "Pro"
  bash_it:
    theme: tylenol
    enabled_plugins:
      completion:
        - defaults
        - bash-it
        - git
        - brew
        - gem
        - rake
        - ssh
      plugins:
        - git
        - ssh
        - ruby
        - rbenv
        - vagrant
