recipes:
  global:
    # general unix setup
    - dotfiles::bash_it
    - dotfiles::gitconfig
    - dotfiles::projects

    # rails development stack
    - rbenv::user_install
    - dotfiles::gem_setup

    # development tools
    - applications::sublime_text_3

attributes:
  workspace_directory: Projects
  dotfiles:
    project_dir: Projects
    projects:
      -
        - thegarage-gitx
        - https://github.com/thegarage/thegarage-gitx.git
      -
        - thegarage-template
        - https://github.com/thegarage/thegarage-template.git
  homebrewalt:
    apps:
      - git
      - phantomjs
      - heroku
      - nodejs
    cask_apps:
      - skype
      - virtualbox
      - vagrant
      - mou
      - github
  rbenv:
    default_ruby: "2.0.0-p353"
    rubies:
      2.0.0-p353: {}
  vagrant_plugins:
    - vagrant-berkshelf
    - vagrant-omnibus
  terminal:
    color_scheme: "Pro"
  bash_it:
    theme: tylenol
    enabled_plugins:
      completion:
        - defaults
        - bash-it
        - git
        - brew
        - gem
        - rake
        - ssh
      plugins:
        - git
        - ssh
        - ruby
        - rbenv
        - vagrant
